root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./counterspell"
  cmd = "go build -o ./counterspell ./cmd/app"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "local", "worktree-*", "data", "node_modules", "ui/node_modules"]
  exclude_file = []
  exclude_regex = ["_test\\.go", "_templ\\.go", "\\.sql\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[server]
  cmd = ";set -o allexport && source .envrc && set +o allexport; ./counterspell -addr :8710 -log server.log"
  delay = 1000
  exclude_dir = []
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = []
  include_file = []
  kill_delay = "0s"
  log = ""
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  stop_on_root = false
